import * as fs from 'fs';
import * as path from 'path';

export class OMPFlowInstaller {
  private targetDir: string;

  constructor(targetDir: string = process.cwd()) {
    this.targetDir = targetDir;
  }

  public install(): void {
    const ompExtensionDir = path.join(this.targetDir, '.omp', 'extensions');
    const ompSkillsDir = path.join(this.targetDir, '.omp', 'skills');

    fs.mkdirSync(ompExtensionDir, { recursive: true });
    fs.mkdirSync(ompSkillsDir, { recursive: true });

    const extensionContent = `// Auto-generated by omp-flow installer
import activateExtension from 'omp-flow/omp/extension';
export default activateExtension;
`;
    fs.writeFileSync(path.join(ompExtensionDir, 'omp-flow.ts'), extensionContent, 'utf-8');

    const skills = [
      {
        name: 'omp-flow',
        content: `---
name: omp-flow
description: Multi-agent workflow orchestration framework integrating Trellis context & Maestro Ralph FSM.
---

# omp-flow OMP Workflow

Slash commands for multi-agent workflow orchestration:
- \`/omp-flow:init\`: Initialize .omp-flow/ workspace
- \`/omp-flow:brainstorm [topic]\`: Multi-perspective design exploration
- \`/omp-flow:plan [intent]\`: Generate PRD & Context Package
- \`/omp-flow:execute\`: Advance Ralph FSM step loop with subagents
- \`/omp-flow:continue\`: Resume active task session & continue step loop
- \`/omp-flow:grill\`: Quality review against boundary contract
- \`/omp-flow:harvest\`: Harvest lessons learned to knowhow
- \`/omp-flow:status\`: View current milestone, phase & FSM status
`,
      },
      {
        name: 'omp-flow-brainstorm',
        content: `---
name: omp-flow-brainstorm
description: Multi-perspective exploratory design and trade-off analysis skill.
---
# OMP-Flow Brainstorm Skill
- Spawns parallel subagent perspectives for tradeoff analysis.
- Persists design options to .omp-flow/tasks/{taskId}/brainstorm.md.
`,
      },
      {
        name: 'omp-flow-architect',
        content: `---
name: omp-flow-architect
description: System architect skill for PRDs & Context Package boundary contracts.
---
# OMP-Flow Architect Skill
- Generates PRD at .omp-flow/tasks/TASK-*/prd.md
- Compiles context-package.json with in_scope/out_of_scope boundaries.
`,
      },
      {
        name: 'omp-flow-researcher',
        content: `---
name: omp-flow-researcher
description: Read-only code and tech scout skill persisting findings to .omp-flow/tasks/{taskId}/research/*.md.
---
# OMP-Flow Researcher Skill
- Read-only code and technology scout.
- Persists research topics into markdown files under .omp-flow/tasks/{taskId}/research/.
`,
      },
      {
        name: 'omp-flow-executor',
        content: `---
name: omp-flow-executor
description: Worker subagent skill for focused code edits inside defined boundaries.
---
# OMP-Flow Executor Skill
- Respects context-package.json boundaries.
- Uses OMP IrcBus to communicate with sibling workers.
`,
      },
      {
        name: 'omp-flow-reviewer',
        content: `---
name: omp-flow-reviewer
description: Quality audit skill for reviewing code changes against boundary contracts.
---
# OMP-Flow Reviewer Skill
- Runs omp_flow_boundary_check to detect code drift.
- Approves step completion status.
`,
      },
      {
        name: 'omp-flow-harvester',
        content: `---
name: omp-flow-harvester
description: Learning skill for harvesting gotchas and recipes to knowhow.
---
# OMP-Flow Harvester Skill
- Scans scratch logs for gotchas and recipes.
- Appends rules to .omp-flow/knowhow/ and .omp-flow/specs/.
`,
      },
      {
        name: 'omp-flow-debugger',
        content: `---
name: omp-flow-debugger
description: Automated failure analysis and gap-fix skill.
---
# OMP-Flow Debugger Skill
- Formulates mini-plans to fix failed test steps.
`,
      },
    ];

    for (const skill of skills) {
      const dir = path.join(ompSkillsDir, skill.name);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'SKILL.md'), skill.content, 'utf-8');
    }
  }
}
